### ISSUE TITLE
Feedback for assignment 1

### ISSUE THREAD

**Issue by timmcginley** [WilliamEskildsen/41934_group3#1]
Good first effort that shows potential!

It is great that you:

* defined a script that works well in BlenderBIM
* correctly named the readme.md file
* wrote a clear use case and description in that md file

Improvements could be:
* call your code main.py if it is the main file and then have special names for any .py files that you ae referencing as modules.

Future work
* The EPD work is really interesting and important work. We should have a couple of speakers coming in to talk about this. Plus you can also talk to @mdjska and @vejlgaarda about it.

**Comment by mdjska** [comment]
Be careful with the quantity areas. Right now, you are getting the equivalent of space areas, which includes 145 m2 of the roof. For LCA analysis, it may be better to count quantities of specific materials or elements, for example 'IfcSlab'. Otherwise good job. :)

**Comment by LucasBaunDantzer** [comment]
We made a subfolder with the images and visualized the BPMN in the readme. Furthermore we changed the name of the code to main.py
